// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StargateAPI.Business.Data;

#nullable disable

namespace StargateApi.Business.Data.Migrations
{
    [DbContext(typeof(StargateContext))]
    [Migration("20260401181633_AddMocksAngularChanges")]
    partial class AddMocksAngularChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CareerEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CareerStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentDutyTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentRank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("AstronautDetails");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CareerStartDate = new DateTime(2013, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDutyTitle = "Artemis Support Crew",
                            CurrentRank = "Mission Specialist",
                            PersonId = 13
                        },
                        new
                        {
                            Id = 3,
                            CareerStartDate = new DateTime(2013, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDutyTitle = "Lunar Gateway Pilot",
                            CurrentRank = "Commander",
                            PersonId = 14
                        },
                        new
                        {
                            Id = 4,
                            CareerStartDate = new DateTime(1998, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDutyTitle = "ISS Commander",
                            CurrentRank = "Captain",
                            PersonId = 15
                        },
                        new
                        {
                            Id = 5,
                            CareerEndDate = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CareerStartDate = new DateTime(1963, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "Major General",
                            PersonId = 16
                        },
                        new
                        {
                            Id = 6,
                            CareerEndDate = new DateTime(2006, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CareerStartDate = new DateTime(1990, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "Colonel",
                            PersonId = 17
                        },
                        new
                        {
                            Id = 7,
                            CareerEndDate = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CareerStartDate = new DateTime(1978, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDutyTitle = "RETIRED",
                            CurrentRank = "Colonel",
                            PersonId = 18
                        },
                        new
                        {
                            Id = 8,
                            CareerStartDate = new DateTime(2013, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDutyTitle = "Flight Engineer",
                            CurrentRank = "Lieutenant Colonel",
                            PersonId = 19
                        },
                        new
                        {
                            Id = 9,
                            CareerStartDate = new DateTime(2017, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDutyTitle = "Mission Commander",
                            CurrentRank = "Major",
                            PersonId = 20
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDuty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DutyEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DutyStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DutyTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("AstronautDuties");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            DutyStartDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DutyTitle = "Artemis Support Crew",
                            PersonId = 13,
                            Rank = "Mission Specialist"
                        },
                        new
                        {
                            Id = 3,
                            DutyStartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DutyTitle = "Lunar Gateway Pilot",
                            PersonId = 14,
                            Rank = "Commander"
                        },
                        new
                        {
                            Id = 4,
                            DutyStartDate = new DateTime(2012, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DutyTitle = "ISS Commander",
                            PersonId = 15,
                            Rank = "Captain"
                        },
                        new
                        {
                            Id = 5,
                            DutyStartDate = new DateTime(1981, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DutyTitle = "RETIRED",
                            PersonId = 16,
                            Rank = "Major General"
                        },
                        new
                        {
                            Id = 6,
                            DutyStartDate = new DateTime(2006, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DutyTitle = "RETIRED",
                            PersonId = 17,
                            Rank = "Colonel"
                        },
                        new
                        {
                            Id = 7,
                            DutyStartDate = new DateTime(1993, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DutyTitle = "RETIRED",
                            PersonId = 18,
                            Rank = "Colonel"
                        },
                        new
                        {
                            Id = 8,
                            DutyStartDate = new DateTime(2021, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            DutyTitle = "Flight Engineer",
                            PersonId = 19,
                            Rank = "Lieutenant Colonel"
                        },
                        new
                        {
                            Id = 9,
                            DutyStartDate = new DateTime(2023, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DutyTitle = "Mission Commander",
                            PersonId = 20,
                            Rank = "Major"
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 13,
                            Name = "Jessica Meir"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Victor Glover"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sunita Williams"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Michael Collins"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Eileen Collins"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Guion Bluford"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Anne McClain"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Jasmin Moghbeli"
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.ProcessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessLog");
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDetail", b =>
                {
                    b.HasOne("StargateAPI.Business.Data.Person", "Person")
                        .WithOne("AstronautDetail")
                        .HasForeignKey("StargateAPI.Business.Data.AstronautDetail", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDuty", b =>
                {
                    b.HasOne("StargateAPI.Business.Data.Person", "Person")
                        .WithMany("AstronautDuties")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StargateAPI.Business.Data.Person", b =>
                {
                    b.Navigation("AstronautDetail");

                    b.Navigation("AstronautDuties");
                });
#pragma warning restore 612, 618
        }
    }
}
