using Microsoft.EntityFrameworkCore;
using StargateAPI.Business.Data;

namespace StargateAPI.Tests;

public class StargateContextTests
{
    [Fact]
    public void Context_HasPeopleDbSet()
    {
        using var context = TestDbContextFactory.Create();

        var person = new Person { Name = "DbSet Test" };
        context.People.Add(person);
        context.SaveChanges();

        Assert.Single(context.People);
    }

    [Fact]
    public void Context_HasAstronautDetailsDbSet()
    {
        using var context = TestDbContextFactory.Create();

        var person = new Person { Name = "Detail Test" };
        context.People.Add(person);
        context.SaveChanges();

        var detail = new AstronautDetail
        {
            PersonId = person.Id,
            CurrentRank = "Colonel",
            CurrentDutyTitle = "Commander",
            CareerStartDate = DateTime.UtcNow
        };
        context.AstronautDetails.Add(detail);
        context.SaveChanges();

        Assert.Single(context.AstronautDetails);
    }

    [Fact]
    public void Context_HasAstronautDutiesDbSet()
    {
        using var context = TestDbContextFactory.Create();

        var person = new Person { Name = "Duty Test" };
        context.People.Add(person);
        context.SaveChanges();

        context.AstronautDuties.Add(new AstronautDuty
        {
            PersonId = person.Id,
            Rank = "Major",
            DutyTitle = "Pilot",
            DutyStartDate = DateTime.UtcNow
        });
        context.SaveChanges();

        Assert.Single(context.AstronautDuties);
    }

    [Fact]
    public void Context_HasProcessLogsDbSet()
    {
        using var context = TestDbContextFactory.Create();

        context.ProcessLogs.Add(new ProcessLog
        {
            Message = "Test",
            LogLevel = "Information",
            Timestamp = DateTime.UtcNow,
            Source = "Test"
        });
        context.SaveChanges();

        Assert.Single(context.ProcessLogs);
    }

    [Fact]
    public void PersonName_HasUniqueIndex()
    {
        using var context = TestDbContextFactory.Create();

        var entityType = context.Model.FindEntityType(typeof(Person));
        var nameIndex = entityType?.GetIndexes()
            .FirstOrDefault(i => i.Properties.Any(p => p.Name == "Name"));

        Assert.NotNull(nameIndex);
        Assert.True(nameIndex.IsUnique);
    }

    [Fact]
    public void PersonName_IsRequired_MaxLength200()
    {
        using var context = TestDbContextFactory.Create();

        var entityType = context.Model.FindEntityType(typeof(Person));
        var nameProperty = entityType?.FindProperty("Name");

        Assert.NotNull(nameProperty);
        Assert.False(nameProperty.IsNullable);
        Assert.Equal(200, nameProperty.GetMaxLength());
    }

    [Fact]
    public void AstronautDetail_HasOneToOne_WithPerson()
    {
        using var context = TestDbContextFactory.Create();

        var person = new Person { Name = "Relationship Test" };
        context.People.Add(person);
        context.SaveChanges();

        var detail = new AstronautDetail
        {
            PersonId = person.Id,
            CurrentRank = "Colonel",
            CurrentDutyTitle = "Commander",
            CareerStartDate = DateTime.UtcNow
        };
        context.AstronautDetails.Add(detail);
        context.SaveChanges();

        var loaded = context.AstronautDetails.First(d => d.PersonId == person.Id);
        Assert.Equal(person.Id, loaded.PersonId);
    }

    [Fact]
    public void AstronautDuty_HasManyToOne_WithPerson()
    {
        using var context = TestDbContextFactory.Create();

        var person = new Person { Name = "Multi Duty Test" };
        context.People.Add(person);
        context.SaveChanges();

        context.AstronautDuties.Add(new AstronautDuty
        {
            PersonId = person.Id,
            Rank = "Major",
            DutyTitle = "Pilot",
            DutyStartDate = DateTime.UtcNow
        });
        context.AstronautDuties.Add(new AstronautDuty
        {
            PersonId = person.Id,
            Rank = "Colonel",
            DutyTitle = "Commander",
            DutyStartDate = DateTime.UtcNow.AddDays(30)
        });
        context.SaveChanges();

        var duties = context.AstronautDuties.Where(d => d.PersonId == person.Id).ToList();
        Assert.Equal(2, duties.Count);
    }

    [Fact]
    public void Person_PrimaryKey_IsAutoGenerated()
    {
        using var context = TestDbContextFactory.Create();

        var person = new Person { Name = "Auto Id Test" };
        context.People.Add(person);
        context.SaveChanges();

        Assert.True(person.Id > 0);
    }
}